"""Check parity between the Python simulator and the static web demo.

The web demo (../epidemic-breakers-web) RE-IMPLEMENTS the simulator in
vanilla JS (sim.js) and bakes in precomputed data exported from this repo
(data/graph.json, data/edge_params.json, data/best_theta.json). This script
verifies the baked-in constants agree with the Python source of truth:

  * 40 nodes / 111 edges, identical edge identity AND order
  * per-edge noise/spread params identical (noiseAmp=0.3, spreadP=0.25)
  * best_theta.json identical to results/best_theta.npy
  * sim.js default sim constants match (cooldown=5, nSteps=40, emaAlpha=0.3)

Known differences (documented, not failures):
  * the JS RNG (mulberry32/cyrb53) differs from numpy's PCG64, so
    individual scenario trajectories differ even for the same seed;
    parity is statistical (mean F over seeds agrees within noise).
  * the web demo's per-edge param regeneration for non-default
    spread/noise uses its own hash; only the baked-in default
    environment is checked here.

Usage: python3 scripts/check_web_parity.py [--web-dir PATH]
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from src import graph_gen
from src.graph_gen import edge_list
from src.simulator import _per_edge_params

PASS, FAIL = "PASS", "FAIL"


def check(name: str, ok: bool, detail: str = "") -> bool:
    print(f"[{PASS if ok else FAIL}] {name}" + (f" -- {detail}" if detail else ""))
    return ok


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--web-dir", default=str(REPO.parent / "epidemic-breakers-web"))
    args = ap.parse_args()
    web = Path(args.web_dir)
    if not web.is_dir():
        print(f"web repo not found at {web} (use --web-dir)")
        return 2

    ok = True
    G = graph_gen.generate_service_graph(n_nodes=40, seed=7)
    py_edges = edge_list(G)
    gj = json.loads((web / "data" / "graph.json").read_text())
    ep = json.loads((web / "data" / "edge_params.json").read_text())
    bt = json.loads((web / "data" / "best_theta.json").read_text())

    ok &= check("graph size 40 nodes / 111 edges",
                gj["n"] == 40 and len(gj["edges"]) == 111 and
                G.number_of_nodes() == 40 and len(py_edges) == 111,
                f"web={gj['n']}/{len(gj['edges'])} py=40/{len(py_edges)}")
    ok &= check("edge identity and order match",
                [tuple(e) for e in gj["edges"]] == py_edges)
    ok &= check("default env constants",
                ep["noiseAmp"] == 0.3 and ep["spreadP"] == 0.25,
                f"noiseAmp={ep['noiseAmp']} spreadP={ep['spreadP']}")

    noise_mat, p_mat = _per_edge_params(py_edges, 40, 0.3, 0.25)
    per_edge = ep["params"]
    same_params = (
        len(per_edge) == len(py_edges)
        and all(pe[0] == u and pe[1] == v for pe, (u, v) in zip(per_edge, py_edges))
        and all(abs(pe[2] - noise_mat[u, v]) < 1e-12 and
                abs(pe[3] - p_mat[u, v]) < 1e-12
                for pe, (u, v) in zip(per_edge, py_edges))
    )
    ok &= check("per-edge noise/spread params identical", same_params)

    npy = np.load(REPO / "results" / "best_theta.npy")
    ok &= check("best_theta.json matches results/best_theta.npy",
                np.allclose(np.asarray(bt, dtype=float), npy))

    sim_js = (web / "sim.js").read_text()
    defaults = {
        "cooldown = 5": r"cooldown\s*=\s*5\b",
        "nSteps = 40": r"nSteps\s*=\s*40\b",
        "emaAlpha = 0.3": r"emaAlpha\s*=\s*0\.3\b",
    }
    for name, pat in defaults.items():
        ok &= check(f"sim.js default {name}", re.search(pat, sim_js) is not None)

    print()
    print("Known differences (not failures): JS RNG streams differ from "
          "numpy, so single-scenario trajectories differ; parity is "
          "statistical. Non-default spread/noise envs are regenerated by "
          "the demo's own hash.")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
